### PR TITLE
Fix issue #891.

### PR DESCRIPTION
**Pull request by boaks**
Forward request for block2 num 0.

Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by boaks** [comment]
@sbernard31 

Please, have also a look on this :-). It changes the blockwise independent from the "strict block2 configuration".

**Comment by mb590721** [comment]
What if the first response block isn't received by the client and that it retransmit its request for the first block, the server would then pass it to the applicative layer instead of transparently retransmitting the response block right ? 

I'm not too sure about the right way to handle this use case, I don't find the RFC on the blockwise very clear about it. I'm not sure neither it's a real problem, I suppose it depends on what is done in the applicative layer.

**Comment by mb590721** [comment]
Or maybe since the client should reuse the same token it will be handled correctly at the server side by another layer ? 

If yes then it seems good to me.

**Comment by boaks** [comment]
> What if the first response block isn't received by the client and that it retransmit its request for the first block, the server would then pass it to the applicative layer instead of transparently retransmitting the response block right ?

No, retransmission is detected by the `MID:address:port` and handled by the deduplication in the `ReliabilityLayer.receiveRequest`. So it will not be passed again to the application layer.

> I'm not too sure about the right way to handle this use case, I don't find the RFC on the blockwise very clear about it.

The deduplication is handled as for any usual request and is defined in https://tools.ietf.org/html/rfc7252#section-4.5 . Blockwise (RFC7959) just uses such request multiple times. The "complex" point will be, that RFC7959 doesn't specify, how to implement that in a "transparent mode". So it's undefined there, when a request is forwarded to the application layer. If a  different processing is required, you may switch off that "californium transparent mode" by configuring "MAX_RESOURCE_BODY_SIZE" to 0.

**Comment by boaks** [comment]
> Or maybe since the client should reuse the same token it will be handled correctly at the server side by another layer ?

The token is a artefact of a single request-response matching. There is no further token relation for blockwise transfers. Californium uses the same token for traceability of the transparent blockwise transfers. But in fact, it should be possible to patch the `BlockwiseLayer`, to use different tokens for the requests.

**Comment by sbernard31** [comment]
This sounds good to me.

Should we add the test in #892 or something similar ?
Too bad we don't check exchange/blocklayer  memory leak in the class `BlockwiseTransferTest` like we do in `BlockwiseServerSideTest`.

**Comment by boaks** [comment]
> Should we add the test in #892 or something similar ?

I would ask @mb590721 to do so, after this PR gets merged.

> Too bad we don't check exchange/blocklayer memory leak in the class BlockwiseTransferTest like we do in BlockwiseServerSideTest.

That's "out of scope" from issue #891.

**Comment by boaks** [comment]
@mb590721 

You made some comments above. do you want to make some more tests about your remarks and my answers? Or should we merge it and you rebase your added test?

**Comment by mb590721** [comment]
No that's ok for me, I was confused about the retransmission but with your explanations I now understand how it works.

You can merge the PR and I will rebase my branch based on the new 2.0.x

**Comment by boaks** [comment]
> You can merge the PR and I will rebase my branch based on the new 2.0.x

Thanks in advance. I appreciate your analysing and testing of the blockwise! If you find the next issue, don't hesitate to report it.

**Pull request merged**
