### PR TITLE
Add DtlsHandshakeTimeoutException in scandium

### LINKED ISSUE #1223: Add a specific exception for HandshakeTimeout ?
In Leshan, when a [request timeout for any reason](https://github.com/eclipse/leshan/wiki/Request-Timeout) we raise a TimeoutException.
We decide recently to consider a Handshake flight timeout as Leshan request timeout.

But currently there no easy way to know handshake timeout because we raise an `Exception`.
So the code looks like something like this : 
```java
    if (error instanceof Exception && error.getMessage().startsWith("Handshake flight")) {
```
Should we raise a specific exception ? 

(Ideally I would like to be able to distinguish a CoAP timeout from a Blockwise timeout but I guess this would be a really more complex task , this is maybe relative to https://github.com/eclipse/californium/issues/818 ?)

### PR DESCRIPTION
**Pull request by sbernard31**
It aims to fix #1223.

### CODE REVIEW

**Comment by sbernard31** [comment]
I don't know if this : 
```java
// limit of retransmissions not reached
// but handshake expired during Android / OS "deep sleep"
message = " Stopped by expired realtime!";
```
should be consider as a timeout.

**Comment by sbernard31** [comment]
Not a big deal, but I didn't get the difference between : 

```java
else if (tries > max) {
	LOGGER.debug("Flight for [{}] has reached timeout, discarding ...", flight.getPeerAddress());
	message = " Stopped by timeout!";
	timeout = true;
} 
```
and
```java
else {
	LOGGER.debug(
			"Flight for [{}] has reached maximum no. [{}] of retransmissions, discarding ...",
			flight.getPeerAddress(), max);
	message = " Stopped by timeout after " + max + " retransmissions!";
	timeout = true;
}
```

**Comment by sbernard31** [comment]
Not linked directly to this PR but I failed to launch single scandium test, neither in eclipse (tests failed) or with maven `mvn -Dtest=DTLSConnectorTest test`  :thinking:

**Comment by boaks** [comment]
> -Dtest=DTLSConnectorTest -DfailIfNoTests=false

on the "parent" works "on my machine".

**Comment by sbernard31** [comment]
It works on my machine too at parent level.

**Comment by boaks** [comment]
> It works on my machine too at parent level.

So, you complain about executing it at module level "scandium"?

**Comment by boaks** [comment]
>  I didn't get the difference between

The first is used for "isEarlyStopRetransmission".

**Comment by boaks** [comment]
> should be consider as a timeout.

I would so.

**Comment by sbernard31** [comment]
> The first is used for "isEarlyStopRetransmission".

I get it now.

> So, you complain about executing it at module level "scandium"?

"Complain" that was not my intention :sweat_smile:. I just share an issue I faced (Mainly to know if this is a shared/intended/known behavior)

> I would so.

Done.

**Comment by boaks** [comment]
LGTM

**Pull request merged**
