### PR TITLE
Add MTU limit.

### PR DESCRIPTION
**Pull request by boaks**
Limit MTU, if auto detected link local MTU is used.
Issue #1260

Signed-off-by: Achim Kraus <achim.kraus@bosch.io>

### CODE REVIEW

**Comment by boaks** [comment]
OK.
So mainly release a 2.3.0 with this changes (I considered to be 2.2.1), and move the current 2.3.0-SNAPSHOT to 2.4.0-SNAPSHOT?

**Comment by boaks** [comment]
Or, adapt PR #1263 and release a 2.2.1 with #1262 and #1263 ?

**Comment by sbernard31** [comment]
No preference, both are OK to me. (maybe release a 2.3 is simpler ?)

**Comment by boaks** [comment]
If it's ok, I would go for 2.2.1 in order not to flood the minor version.

**Comment by sbernard31** [comment]
you mean without this PR and with #1263 adapted ?

**Comment by boaks** [comment]
> you mean without this PR and with #1263 adapted ?

Yes.

**Comment by sbernard31** [comment]
Ok, no objection :)

**Comment by boaks** [comment]
I create a PR for the master.

**Pull request closed without merging**
