### PR TITLE
[#511] Include virtual host in DtlsEndpointContext matching.

### PR DESCRIPTION
**Pull request by sophokles73**
Make sure that messages destined for host X are not sent over a DTLS
session established with host Y.

### CODE REVIEW

**Comment by boaks** [comment]
Is there any difference in `RelaxedDtlsEndpointContextMatcher` and `StrictDtlsEndpointContextMatcher` according the usage of the introduced `isSameVirtualHost`?

Or was the main intention of that, the using TLS may fail?

**Comment by boaks** [comment]
I would prefer to add a parameter to the `KeySetEndpointContextMatcher` constructor, which defines, if the `isSameVirtualHost` is tested or not.

**Comment by sophokles73** [comment]
> Is there any difference in RelaxedDtlsEndpointContextMatcher and StrictDtlsEndpointContextMatcher according the usage of the introduced isSameVirtualHost?
Or was the main intention of that, when using TLS, it may fail?

Yes, both matchers should consider the virtual host, shouldn't they?

**Comment by sophokles73** [comment]
> I would prefer to add a parameter to the KeySetEndpointContextMatcher constructor, which defines, if the isSameVirtualHost is tested or not.

You mean, introducing this flag instead of overriding the *isResponseRelatedToRequest* and *isToBeSent* methods?

**Comment by boaks** [comment]
> You mean, introducing this flag instead of overriding the isResponseRelatedToRequest and isToBeSent methods?

Yes! 
It would make it also a little easier, to enable that for coap over tls, when that implementation is updated to also fully support SNI.

**Pull request merged**
