### PR TITLE
Use full-handshake for resumption with empty session id.

### PR DESCRIPTION
**Pull request by boaks**
Add no server session id to configuration.
Use creation time for endpoint context, if session id is empty.

Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by boaks** [comment]
#845 for 2.0.x.

If "more" server don't provide a session id than the tradfri gateway, the endpoint context must use something else for matching endpoint contexts

**Comment by sbernard31** [comment]
LGTM.

So currently, for session without session id, we use the creation time as identifier.
Meaning that 2 sessions which are created as the same time would have the same identifier. A bit strange but probably not an issue as conflict seems really improbable.

Just in case, some idea to replace that :
As resumption and re-negociation are not allowed that means that this session is strongly bound to the connection, so having a kind of connection id would help. (it would also help to implement a real STRICT endpoint context matcher), so we could :
1. a generate a connection id.
2. or maybe we could find a kind of connection identifier in DTLSConnectionState ?

**Comment by boaks** [comment]
> currently

with cid #824 each connection has a id (unique for a period, so appended with the time, unique), which could then be used. Until yesterday, I didn't even know, that some servers may use empty session id's. So I don't think, this temporary fix will harm.

Otherwise, If you have a lot of time, should we include the cid into M13? :-)

**Comment by sbernard31** [comment]
I'm OK to integrate it like this.
My comments was just to feed the reflexion for future changes.

So it's good to merge professor ! :p

**Comment by boaks** [comment]
My hint to #824 was, that I hope it's the very near future.

**Pull request merged**
