### PR TITLE
Update HttpTranslator.java

### PR DESCRIPTION
**Pull request by nicom24**
Added translation compatibility for DTLS connections with coaps://

### CODE REVIEW

**Comment by mkovatsc** [comment]
Can you please fill a CLA: https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#Eclipse_Foundation_Contributor_License_Agreement

It needs to match your commit e-mail.

Alternatively, I can commit this small fix, but then you will not appear among the committers :)

**Comment by nicom24** [comment]
Done, thanks :)
I'm also trying to implement https security on the proxy for my thesis, I hope to update again soon

**Comment by mkovatsc** [comment]
Fixed in 931ed30.

What is your status in general? :)

**Comment by nicom24** [comment]
@mkovatsc I finished my thesis and graduated :)
I uploaded all my work in my repository if you want to have a look at it!
https://github.com/nicom24/IoTSecurityFramework

**Pull request closed without merging**
