### PR TITLE
Improve exceptions thrown by CoapClient.synchronous()

### PR DESCRIPTION
**Pull request by aml2610**
Proposed fix for https://github.com/eclipse/californium/issues/920

### CODE REVIEW

**Comment by boaks** [comment]
LGTM for me. 

There is a "anonymous merge commit" which violates the contribution checks of eclipse.
I would try to "recreate" the PR by cherry-picking the commits (without the merge-commit) on top of the 2.0.x.

**Comment by boaks** [comment]
And please squash your resulting commits into a single commit.

**Comment by aml2610** [comment]
Right, thanks, done @boaks

**Comment by sbernard31** [comment]
LGTM

**Pull request merged**
