### PR TITLE
Update NettyContextUtils to store the peer certificate chain

### PR DESCRIPTION
**Pull request by AlexITC**
While using TLS, we try to get the peer certificate chain (X509CertPath) or
fallback to get the peer principal (X500Principal).

### CODE REVIEW

**Comment by AlexITC** [comment]
@boaks Here are the changes that we talked on #548, I have some hard feeling on moving the `X509CertPath` to the `element-connector` module because there are similar classes that still live in `scandium`, maybe should we also move them? or creating a new module for these classes only might be the right move.

What do you think?

**Comment by boaks** [comment]
> I have some hard feeling on moving the X509CertPath to the element-connector module because there are similar classes that still live in scandium, maybe should we also move them? or creating a new module for these classes only might be the right move.

I have the same feelings, but as written frequently, I want to concentrate first on issue #429 .

Your approach serialize an deserialize the `certificate[]`. I would prefer a implementation similar to `CertificateMessage.setCertificateChain` and there for move that to X509CertPath (e.g. as 
`X509CertPath fromCertificatesChain(Certificate[] certificateChain) ` and `CertPath generateCertPath(Certificate[] certificateChain)` to also use it then from the `CertificateMessage`.

So, this smells for me, that there is more "common encryption" functionallity, and therefore, after issue #429, I guess we should discuss, if this should go to an own module.

**Comment by boaks** [comment]
@AlexITC 
maybe you can check branch "certpath" where I added the above mentioned changes if it works for you.

**Comment by AlexITC** [comment]
great, thanks!

**Comment by boaks** [comment]
The idea to move the scandium `auth` package (or currently only the `X509CertPath` class) was from my side, because in my opinion a dependency to scandium only for reuse of the `Principal` implementation seems for to be not that good.

**Comment by sbernard31** [comment]
I'm also not so comfortable with the idea of making element-connector-tcp depend on scandium

**Comment by AlexITC** [comment]
as I remember, moving the `X509CertPath` was a requirement to avoid circular dependencies.

**Comment by boaks** [comment]
@sophokles73 

Do you refuse this PR? 
Otherwise I would like to got for merging it.

**Comment by boaks** [comment]
Just to be precise, I want to merge branch 'certpath'. 
So I create a PR for that.

**Comment by boaks** [comment]
OK, so first merge this, and the create a PR to certpath :-).

**Pull request merged**
