### PR TITLE
Change output level of some logs in DTLSConnector.

### PR DESCRIPTION
**Pull request by sbernard31**
I try to change log level according to https://github.com/eclipse/californium/issues/1276#issuecomment-613313675.

I also use DROP_LOGGER on `GeneralSecurityException` to be consistent with https://github.com/eclipse/californium/pull/1277/files#diff-f37db83612e8b31e5a34aeaab5710866R2355
(I'm not sure this is a good idea, let me know :))

(first commit is cherry pick of #1277)

### CODE REVIEW

**Comment by boaks** [comment]
LGTM

**Comment by sbernard31** [comment]
should I backport this in master ? (do you prefer I create a PR or backport directly?)

**Comment by boaks** [comment]
> should I backport this in master ? 

If you want. no preferences for a way to do it.

**Comment by sbernard31** [comment]
56344cb cherry picked in master (commit b4e0f1fcbf91990abbb122c14997a60add0ce9c8)

**Pull request merged**
