### PR TITLE
Reduce synchronization in blockwise layer.

### PR DESCRIPTION
**Pull request by boaks**
Experimental. There are not too much block1 tests. Adding them will take longer.

Signed-off-by: Achim Kraus <achim.kraus@bosch.io>

### CODE REVIEW

**Comment by boaks** [comment]
@sbernard31 

I'm not sure, if it is possible for you to test that in your setup. If that is possible, we can create a 2.6.x branch and pick this into that.

**Comment by sbernard31** [comment]
I looked at the PR and that sounds OK at first sight.

> I'm not sure, if it is possible for you to test that in your setup

We have not so much tests on our side too. I can try to run it tomorrow but I'm pretty sure there are not able to detect any race condition issue which could be introduce because of not enough lock.

**Comment by boaks** [comment]
I extended the benchmark in cf-extplugtest-client.
We see, if runs stable. But I guess, it will not show the dead-lock you have reported.
Let's see. If these test doesn't show defects, should I create a 2.6.1-M1 in order that you may test, if that works better for you?

**Comment by boaks** [comment]
From my side:
The unit test have run through the night without trouble.
The benchmark with block1 also run without reporting errors.

That doesn't verify, that this resolves the reported issue.

So, I will merge it to the 3.0.

@sbernard31 
If you also want a 2.6.1 or a 2.6.1-M1, let me know.

**Comment by sbernard31** [comment]
> But I guess, it will not show the dead-lock you have reported.

I agree. You need to block one thread for ever on `onResponse` from block1 request to check this.

>That doesn't verify, that this resolves the reported issue.

I agree but reading the code I'm pretty sure, `onresponse` is not out of sync block which was the main issue I guess. My concern about this PR would be more about removing too much `synchronize`.

>  The unit test have run through the night without trouble.

That's good ! A good hint that you don't remove too much `synchronize`.

> I will merge it to the 3.0.

:+1: 

> If you also want a 2.6.1 or a 2.6.1-M1, let me know.

I think this should be good to backport this in a 2.6.x branch, but there is no urgency for release, let's wait a little bit in case we face more important issue and release for more than this optimization.

**Pull request merged**
