### PR TITLE
Secure Client example

### PR DESCRIPTION
**Pull request by allhateme**
An example of Secure Client for the exisisting Secure Server.

### CODE REVIEW

**Comment by sophokles73** [comment]
@allhateme,

thanks for submitting the example for a secure client. In order for us to be able to merge the PR we need you to include a proper signed-off-by footer in the commit message. Can you add this?

Regards,
Kai

**Comment by allhateme** [comment]
@sophokles73 

i filled an LCA, Could you explain me how i can modify the commit in order to add signed-off-by line?

**Comment by sophokles73** [comment]
You can use `git commit --amend` to edit the last commit message. Simply add the corresponding line (after a blank line) to the commit message. Then force push your branch to your git repo from where you created the PR.

**Comment by allhateme** [comment]
@sophokles73 

i modified the commit message. What else have i to do?

Regars, 
Antonio

**Comment by mkovatsc** [comment]
It looks like you added the line hand (others have a colon after "Signed-off-by"). Another problem might be that the author name and Signed-off-by name differ.

Let's try:
1. Change your Git author name for this repo (`git config user.name "Antonio Ciancio"`)
2. Revert your master to de6f1932a19a948cedb073100520874a6133361e (before the merge)
3. Amend you commit with the "-s" option (`git commit --amend -s`)
4. Force-push again to your origin branch

**Pull request closed without merging**
