### PR TITLE
To not drop FINISHED message when receiving it before CIPHERCHANGESPEC

### PR DESCRIPTION
**Pull request by sbernard31**
If FINISHED message is receive before CIPHER CHANGE SPEC, we will drop it because we have an ongoing handshake and the epoch does not match.

We should not drop it but give it to the handshaker which will queue it then processing it later.

This fixed is needed to move forward about access to psk store in an asynchronous way.

(No directly linked to this PR, but I would like to replace `LatchDecrementingDataHandler` by the RecordCollector I introduce in this PR, seems more readable to me)

### CODE REVIEW

**Comment by sophokles73** [comment]
In general, this looks good to me. I seems like a lot of effort required to test that the FINISHED message is forwarded to the handshake (*processing stage*), though. I was wondering whether we can make this kind of test much simpler if we build it on top of the changes introduced in PR #229. We could then simply create a mock `RecordProcessor` which would assert that all records are indeed forwarded to the processing stage, regardless of epoch. WDYT?

**Comment by sbernard31** [comment]
I don't know I like the idea to check that the full handshake is ok.

**Comment by sophokles73** [comment]
I do like that too in general but wouldn't we need to add tests for all possible permutations of *out-of-order* handshake messages as well? The unit tests for the `Handshaker` class already do test some of these so we might be able to add the missing ones there with a little less effort? Just an idea to save some code ... however, I have no problem with leaving it as is ...

**Comment by sbernard31** [comment]
I'm not sure to understand, but I add the tests in DTLS connector as the bug was in DTLS connector. I mean adding the test in handshaker tests does not cover it.

**Comment by sophokles73** [comment]
I know, the bug in `DTLSConnector` is just that it doesn't forward records from a future epoch to the processing stage. So the test might just be to ensure that it does. No need to make sure that the handshake itself succeeds. The tests for `Handshaker` then make sure that the records are actually processed in the correct order ...

**Comment by sbernard31** [comment]
You're right the test I write is pretty high level and cover more than the fix I made.
You would like more low level tests which cover more bad order cases. I agree this could be valuable  but this is not really what I aim to achieve here. You're right the main thing I want to test is that records from a future epoch are forwarded to the processing stage. But even with the new RecordProcessor, I'm not sure I was able to do that easly. (Maybe when RecordProcessor will be extract from DTLSConnector).

Anyway, even if it's a bit complex, I try to make it readable.I think having one functional tests like this can make sense. (This is less sensitive to internal refactoring). (But this is not a strong opinion)

**Comment by sophokles73** [comment]
Absolutely, please go ahead and merge the PR :-)

**Pull request merged**
