### PR TITLE
Add support for setting ThreadGroup for workers

### PR DESCRIPTION
**Pull request by crea-doo**
I'm using Californium in an OSGi environment for client connections and want to be able to stop and restart these connections. I'm aware of the fact that Californium was not designed with enabling restarts of connections in mind (like written in #936) but wanted to enable this use case:

I got a couple of `java.lang.IllegalThreadStateException` exceptions (similar to the one described in #680) but was able to overcome most of them using the provided setters for custom executors.

Unfortunately the `Worker` defined in the [DTLSConnector](https://github.com/eclipse/californium/blob/2.0.x/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L2267) uses the static ThreadGroup `SCANDIUM_THREAD_GROUP` defined in the `NamedThreadFactory`.

This pull requests adds functionality to be able to set a custom ThreadGroup for these workers - the default behaviour doesn't change though.

### CODE REVIEW

**Comment by boaks** [comment]
If that is the only cure, which helps, we may integrate it.

But I'm pretty sure, that there are better solutions than restart the dtls connector frequently on errors without analysing them.

In many cases, it's just a missing "dtls session management", caused by unaware "endpoint" (address:port) changes from NATs. 

Did you try to use the `setAutoResumptionTimeoutMillis` (30000 for 30s are a good first value)?
Or `DTLSConnector.forceResumeSessionFor / forceResumeAllSessions` ?

**Comment by boaks** [comment]
If you just want to support the OSGi start/stop service, OK.
But may be you could provide the stacktraces so that we can check for the cause??

**Comment by crea-doo** [comment]
Yes, I just need that for OSGi and start/stop functionality.

Here is the stacktrace:

```
java.lang.IllegalThreadStateException: null
	at java.lang.ThreadGroup.addUnstarted(ThreadGroup.java:867) ~[?:?]
	at java.lang.Thread.init(Thread.java:405) ~[?:?]
	at java.lang.Thread.init(Thread.java:349) ~[?:?]
	at java.lang.Thread.<init>(Thread.java:535) ~[?:?]
	at org.eclipse.californium.scandium.DTLSConnector$Worker.<init>(DTLSConnector.java:2268) ~[54:my.hwabstraction.tradfri:1.0.12.SNAPSHOT]
	at org.eclipse.californium.scandium.DTLSConnector$5.<init>(DTLSConnector.java:638) ~[54:my.hwabstraction.tradfri:1.0.12.SNAPSHOT]
	at org.eclipse.californium.scandium.DTLSConnector.start(DTLSConnector.java:638) ~[54:my.hwabstraction.tradfri:1.0.12.SNAPSHOT]
	at org.eclipse.californium.scandium.DTLSConnector.start(DTLSConnector.java:528) ~[54:my.hwabstraction.tradfri:1.0.12.SNAPSHOT]
	at org.eclipse.californium.core.network.CoapEndpoint.start(CoapEndpoint.java:401) ~[54:my.hwabstraction.tradfri:1.0.12.SNAPSHOT]
	at org.eclipse.californium.core.CoapClient.setEndpoint(CoapClient.java:349) ~[54:my.hwabstraction.tradfri:1.0.12.SNAPSHOT]
	...
	at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:84) [41:org.apache.karaf.shell.core:4.2.6]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:68) [41:org.apache.karaf.shell.core:4.2.6]
	at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:86) [41:org.apache.karaf.shell.core:4.2.6]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:599) [41:org.apache.karaf.shell.core:4.2.6]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:526) [41:org.apache.karaf.shell.core:4.2.6]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:415) [41:org.apache.karaf.shell.core:4.2.6]
	at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:416) [41:org.apache.karaf.shell.core:4.2.6]
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229) [41:org.apache.karaf.shell.core:4.2.6]
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59) [41:org.apache.karaf.shell.core:4.2.6]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

It seem to be related to the static ThreadGroup `SCANDIUM_THREAD_GROUP` defined in the `NamedThreadFactory`. When a ThreadGroup is stopped or destroyed there is no way of restarting it (see https://docs.oracle.com/javase/7/docs/api/java/lang/ThreadGroup.html#destroy() ) except instantiating a new one.

**Comment by boaks** [comment]
If possible, please check, if the fix in PR #978 works for you.

**Comment by crea-doo** [comment]
Yes, the fix in PR #978 works and makes this one obsolete.
Thanks a lot!

**Comment by boaks** [comment]
Thanks for testing!

**Pull request closed without merging**
