### PR TITLE
[bug #75] Use Request#type at CoapClient#send when specified

### PR DESCRIPTION
**Pull request by evgeniynickolaev**
Signed-off-by: Eugene Nikolaev <eug.nikolaev@gmail.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=75

**Comment by evgeniynickolaev** [comment]
Could you please revise this pull request?
It is related to https://github.com/eclipse/californium/issues/75

Not sure it behaves like it was intended..

**Comment by sophokles73** [comment]
Hi @evgeniynickolaev,

thanks for submitting :-) Could you please check my reply to #75 and see whether it makes sense to you?
I would like to close this PR based on what I wrote because I think that `CoapClient` already offers functionality for achieving what you and @wiinguyen seem to try to accomplish...

**Comment by evgeniynickolaev** [comment]
Closing as it is will be replaced with another pull request

**Pull request closed without merging**
