### PR TITLE
Fix proactive cancel observation, when not using coapclient.

### PR DESCRIPTION
**Pull request by boaks**
Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by sbernard31** [comment]
Could you explain the expected behavior with this fix ?

My tests show that :
1. Notification during ongoing proactive request is still RST.
2. Now the response of the cancel response is also visible via notification listener, I don't think this is a good behavior.
3. Observe relation will be canceled (removed()) at client side for any response which does not contains the observe option. So even if the response of the cancel request is something like METHOD_NOT_ALLOWED or NOT_IMPLEMENTED. Depending on how you interpret the specification this could be acceptable.

**Comment by boaks** [comment]
1. sure, I still see no argument to change that.

2. why? The behaviour **before** this PR would be, to forward all responses (except the first), even those responses which indicates, that the observation is removed by the coap-server. See commit 
d9a993905d1ff4c24dc1bef8ad26bcf581cc202f and issue #465.

3.  "METHOD_NOT_ALLOWED or NOT_IMPLEMENTED" smells for me like "chaos". I'm not sure, why a valid "cancel observation request" should be responded with that response code. And sure, if the "token" is used for chaos, then unexpected things will happen.

**Comment by boaks** [comment]
Just to mention:
Feel free to clean-up the "in between" stuff and provide a clean (and so recommendable) low-level API for the "new" observe stuff (the 2 years ago stuff). If you do so, and you want to provide a alternative implementation for a"proactive cancel" which fulfils more your ideas around the functionality, feel also free to do so. 

As I wrote in 
https://github.com/eclipse/californium/pull/692#discussion_r201319616

> So at least, this seems for me to be not recommended.     
 
I would not recommend to use observe without the `CoapClient`, and therefore, I do not insist in this PR. I provided it more or less, because currently the "low level API" adds the observe to the observation store and so I thought, it should also remove it.

**Comment by boaks** [comment]
@sbernard31 
Do you work on a better solution addressing your 3 topics?

Otherwise, though in my opinion the 3 topics are "as intended by me", do you prefer not to merge this PR even without an alternative solution?

**Comment by sbernard31** [comment]
I need to think a bit more about this, so I would prefer to not merge this for now. (I think this is not so important for the M11 too as coapclient works as expected)

**Comment by boaks** [comment]
OK.

**Comment by sbernard31** [comment]
I sum up my thought here.

My first intuition was CoAP endpoint client was a low level API more complex but flexible to use. (meaning you can do some strange things with it)
In this spirit, I saw : 
 - 1 API to remove the observation at server side was `endpoint.cancelObservation(token)`
 - 1 API to sending a cancel request which only impact relation at server side.
That's why I expected naively.

If this behavior was straight forward to implement I will go for it.
Now we see that implement this would require some corner case in the matcher.
The question is : "Does it worth it ?"

I think most of the time you want to first remove Observation from store (`endpoint.cancelObservation`) and then eventually send a proactive cancel request. So in that case all this details does not really matter and so I would not make the matcher more complex for that.

So,
- If you think we should make this corner case behavior more consistent, I could take time to try to change it in the way I describe above.
- If you think this a corner case we don't really need to support, I would prefer to not integrate this PR as I'm not sure this bring a really more consistent behavior.
- If you really prefer to integrate this PR, go for it, as I said before I do not see a use case where you don't cancel the observation before to send the proactive cancel request anyway.

**Comment by boaks** [comment]
No, as I wrote, I'm not insist in this PR. But then, please cleanup PR #692 to not contain tests, which just show, that this is not fixed :-).

**Comment by sbernard31** [comment]
> But then, please cleanup PR #692 to not contain tests, which just show, that this is not fixed :-).

I will do it ^^

**Pull request closed without merging**
