### PR TITLE
Add tests about transparent block2 transfert

### PR DESCRIPTION
**Pull request by sbernard31**
Issue #355 reveal some problems about concurrent block2 transfer.

Here is the different scenario :
a) A pending blockwise notification interrupted by a new blockwise GET request.
b) A pending blockwise notification interrupted by a new blockwise notification.
c) A blockwise GET request. interrupted by a new blockwise GET request.
d) A blockwise GET request interrupted by a new notification.

a) should be covered by #357
b) by #355

This PR should cover c) and d).

### CODE REVIEW

**Comment by boaks** [comment]
LGTM.

Maybe we add some documentation about the resolving of the "concurrent transfers" for the "transparent blockwise implementation"?

**Comment by sbernard31** [comment]
I can add some documentation. Should I add it in BlockwiseLayer.java ?

I have just noticed that the test `testBlockwiseGetInterruptedByBlockwiseNotification` I added in `OberveClientSideTest` in almost the same than `testBlockwiseGetAndNotify`

should I remove one of them ? maybe the new one is a little bit more complete. (as it checks the request is cancelled and try to send "get block" during the "notification block transfer")

**Comment by boaks** [comment]
> I can add some documentation. Should I add it in BlockwiseLayer.java ?

I would appreciate that.

> should I remove one of them?

I agree, remove the old one.

**Comment by sbernard31** [comment]
Done :)

**Comment by boaks** [comment]
LGTM

**Pull request merged**
