### PR TITLE
Server Name Indication Extension doesn't include server_name_list length field

### PR DESCRIPTION
**Pull request by kiemlicz**
Testing with mbedTLS reveals that mbed's client_hello sni extension cannot be decoded. 
This is due to missing server_name_list length field (encoding and decoding) in extension (as required for vectors).

### CODE REVIEW

**Comment by sophokles73** [comment]
Thanks for the PR. However, you will need to sign an Eclipse CLA as described in the [contribution guide](https://github.com/eclipse/californium/blob/master/CONTRIBUTING.md).

Please also make sure to use tabs instead of spaces in order to prevent breaking indentation ...

**Comment by kiemlicz** [comment]
I've just registered and signed ECA (like a 10 minutes ago) - sorry for inconvenience.
I believe I didn't change your indentation style

**Comment by sophokles73** [comment]
Ok, I have checked your commits.
1. You did not include a `signed-off-by` footer in your commit messages. This is required by the Eclipse IP process. Please take a look at our contribution guide regarding how to add it to your commit message(s).
2. You are using blanks for indentation instead of tabs as we do in the Californium code.
3. It would be nice if you could squash your commits into a single one since they all concern the same issue and one alone doesn't fix the problem.

It would be great if you could change your PR accordingly so that we can accept it :-)
Let em know if you need any further assistance.

**Comment by kiemlicz** [comment]
As usually my experiments went wrong...
Please excuse and close/reject this.

[This one is valid](https://github.com/eclipse/californium/pull/163)

**Pull request closed without merging**
