### PR TITLE
Ability to define custom root resource and MessageDeliverer implementation

### PR DESCRIPTION
**Pull request by ashvayka**
added new constructor to CoapServer class & updated access to deliverRequest method in ServerMessageDeliverer class. This is useful when you would like to define more complex MessageDeliverer logic.

### CODE REVIEW

**Comment by boaks** [comment]
Hi @ashvayka ,

thanks for your interest. I would like to split the extension:

1. If a custom message deliverer should be used, isn't the already available 
`CoapServer.setMessageDeliverer(final MessageDeliverer deliverer)` working? 

2. custom root resource. I'm not sure, if the  idea is only to adapt the text. If so, I would prefer to make that text adaptable using something as "setRootContent(String)". Or do you want to adapt more? If you want to adapt more, please obey, that the root-resource should override the `Resource.getEndpoints()`.  

The error above is caused by a missing ECA, please read [CONTRIBUTING](https://github.com/eclipse/californium/blob/master/CONTRIBUTING.md) for instructions.

**Comment by sbernard31** [comment]
About using a custom root resource, this is something we use in Leshan too.
Currently we do it like this : 
```java
// create coap server
CoapServer coapServer = new CoapServer(coapConfig) {
    @Override
    protected Resource createRoot() {
        return new MyRootResource(this);
    }
};
```

**Comment by boaks** [comment]
Hi @ashvayka ,

is it mainly for hiding the root resource? Should "discover" (".well-known") also be disabled?

Hi @sbernard31 ,

should we add a flag to disable the root resource? Additional also the ".well-known"?

**Comment by sbernard31** [comment]
In Leshan this is not for disable the root resource be really to implement a custom one.
Eg. for Leshan client delete or discover on "/" is possible

**Comment by ashvayka** [comment]
Hi @boaks, I believe the solution provided by @sbernard31 is sufficient for us. We just thought that setting the root resource explicitly in a constructor is a more obvious way for most of the users. What we trying to do is a bit specific. Some of the devices  wrongly construct a COAP URI Path object. The URI e.g. /api/v1/rtddt6576g/telemetry is just one object and COAP server on ThingsBoard expects it to be separate URI Path objects eg /api, /v1, / rtddt6576g, /telemetry. So, we want to create a custom message deliverer that will be "fixing" this. I can close this PR but I would really suggest considering adding at least the ability to set root Resource in the constructor. If you like this, we will submit another PR.

**Comment by boaks** [comment]
> but I would really suggest considering adding at least the ability to set root Resource in the constructor. If you like this, we will submit another PR.

Generally, yes.
One open question would be, how that "Resource.getEndpoints()" stuff will work.
Alternatively, adding the leshan example to the javadoc may also help others.

**Comment by boaks** [comment]
> Some of the devices wrongly construct a COAP URI Path object. The URI e.g. /api/v1/rtddt6576g/telemetry is just one object and COAP server on ThingsBoard expects it to be separate URI Path objects eg /api, /v1, / rtddt6576g, /telemetry.

I'm little mixed up.

What doesn't work is 

```java
CoapServer.add(new CoapResource("api/v1/");
```

What works is 

```java
CoapResource v1 = new CoapResource("v1");
CoapResource api = new CoapResource("api");
api.add(v1);
CoapServer.add(api);
```

**Comment by ashvayka** [comment]
the device firmware has a bug and we can't fix it because we don't control the firmware. According to the [RFC section 5.10.1](https://tools.ietf.org/html/rfc7252#section-5.10.1), the URI Path option should hold only one segment (one segment =
"api", one segment = "v1") but the device sends "api/v1" as one URI Path option.

**Comment by boaks** [comment]
> but the device sends "api/v1"

Ah, OK. Yes, then a custom deliverer helps.

**Comment by boaks** [comment]
I checked the usage of that `CoapResource.getEndpoints()`. AFAIK, it's used for "createClient", which seems to be only used by the `AnnounceResource` in cf-benchmark-observer. There it is easy to get the receiving endpoint from the Exchange. Using an other server endpoint may fail, because that changes the source-address of outgoing messages and may get blocked by NATs.

With that, I think removing `CoapResource.getEndpoints()` is the right way.
And adapt the createClient to use an additional CoapExchange/Endpoint to determine the outgoing endpoint.

So, your PR with a explicit `RootResource` will be welcome.

**Comment by sbernard31** [comment]
@ashvayka, about deliver, if I understand you correctly a possible workaround could be to override : `org.eclipse.californium.core.server.resources.Resource.getChild(String)`

**Comment by boaks** [comment]
See PR #1559 removes the `Resource.getEndpoints()`.
A PR with the root-resource could be based on that.

**Comment by ShvaykaD** [comment]
Hi @boaks  and @sbernard31, after additional investigation, we have noticed that in order to achieve our goal, we can simply create our own message deliverer that will extend `org.eclipse.californium.core.server.ServerMessageDeliverer` class, and override next method:

```
	protected Resource findResource(Exchange exchange) {
		return findResource(exchange.getRequest().getOptions().getUriPath());
	} 
```
with our own implementation that updates UriPath of Exchange before actually calling org.eclipse.californium.core.server.resources.Resource.getChild(String) method.


@sbernard31, idea with overriding method: org.eclipse.californium.core.server.resources.Resource.getChild(String) may work also, but it will basically only fixed the result of org.eclipse.californium.core.server.ServerMessageDeliverer.findResource(final List<String> list) method, and we will still need to do additional logic for parsing URI paths in the resources implementation.

So, probably for the current stage, you can close this pull request.

**Comment by boaks** [comment]
> with our own implementation that updates UriPath of Exchange before actually calling 

That make sense.

**Pull request closed without merging**
