### PR TITLE
FETCH/PATCH framework added and tests updated

### PR DESCRIPTION
**Pull request by T0bbe**
OSCORE processing uses FETCH as dummy value during Observe, see [OSCORE draft](https://github.com/core-wg/oscoap). OSCORE also supports PATCH.

### CODE REVIEW

**Comment by boaks** [comment]
Hi @T0bbe,

first, thanks for your contribution. The last years we used to add stuff mainly in the "squashed rebased" variant. Means make all your changes in 1 commit on the top of the branch you want to contribute. In a few cases we make several commits, but FMPOV your contribution fits into 1 commit. Do you need assistance for the git preparation?

**Comment by T0bbe** [comment]
You can delete this PR. I will do a new PR. Sometimes the commits are not properly signed and sometimes it works.

**Comment by boaks** [comment]
Let me give you some hints:
If you are not a commiter, never work on the main branches, for cali: NOT 1.0.x, master, nor 2.0.x!!!
NEVER!

Prepare your work using a feature branch. e.g. checkout a new branch "fetch_patch". Then prepare your changes on this. During the PR discussion, the base branch (e.g. 2.0.x) may be changed by other PRs. Then update your local 2.0.x branch, rebase your feature, RETEST, and the push forced on that feature branch. Depending on the size of the PR, it may be good to have some commmits to discus, but in the end we usually squash all commits and rebase/merge then this 1 commit to the main branch.

**Comment by boaks** [comment]
I fetched your repo to check what you did. If you use eclipse IDE the steps to prepare the PR are "easy".

Switch to git perspective and open the history view there. 
Rename your 2.0.x branch just into "temp" (with the merge commits on the top).
Then fetch the eclipse repo and checkout the remote 2.0.x branch again (in repos- > californium -> branches -> remote tracking -> origin/2.0.x).
Create your feature branch "fetch_patch".
After that, just cherrypick the commit e5a3ec on that branch.
Test.
The push that feature branch to your github clone and create the PR.

**Pull request closed without merging**
