### PR TITLE
Bugfix of wrong payload length in message tracing for responses.

### PR DESCRIPTION
**Pull request by boaks**
Move common tracing code from Request and Response to Message.
Add textual description for block option.

Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by mkovatsc** [comment]
The commit is fine except for a little code style issue: conditions in if statements should start in the same line as the closing brace. There also some extra spaces.
(We use the default Eclipse code formatter, but without line length restriction.)

Simply commit to the same branch and it will end up here.

**Comment by boaks** [comment]
I'm wondering what you exactly mean by "conditions in if statements should start in the same line as the closing brace". 

if (condition) {
 .... some
} // closing brace

but how can the "condition" start at the line of the "closing brace"?

**Comment by mkovatsc** [comment]
Sorry, I meant additional conditions (else if) and else like in Utils.java:75:
```
}
else {
```

**Comment by mkovatsc** [comment]
Thanks a lot for the contribution!

**Pull request merged**
