### PR TITLE
Move certificate supported check to local field.

### PR DESCRIPTION
**Pull request by boaks**
Fixes leshan issue 964.

Signed-off-by: Achim Kraus <achim.kraus@bosch.io>

### CODE REVIEW

**Comment by sbernard31** [comment]
I was just going to ask if local field should not be used as this object seems to be shared between several Server handshaker. :-)

**Comment by boaks** [comment]
Yes, the local field approach was very, very bad ;-(.

**Comment by sbernard31** [comment]
I tried to understand the code but I feel I missed something ? 

In : 
```java

	@Override
	public boolean select(CipherSuiteParameters parameters) {
		boolean certificateSupportChecked = false;
		for (CipherSuite cipherSuite : parameters.getCipherSuites()) {
			if (cipherSuite.requiresServerCertificateMessage()) {
				if (!certificateSupportChecked) {
					if (select(cipherSuite, parameters)) {
						return true;
					}
					certificateSupportChecked = true;
				}
			} else if (select(cipherSuite, parameters)) {
				return true;
			}
		}
		return false;
	}
```

I see that if we find a cipher suite which requires Server certificate message.
We try to select it. 
If we failed to select it, we never retry a cipher suite which requires server certificate message.
Maybe this is totally correct, but at first sight tat could sounds like a bug because `select` depends on a given cipher suite and failing for a given cipher will make fail for all others.
(I'm not sure I'm clear :grimacing:)


I maybe something like this could be easier to read ? 
```java
	@Override
	public boolean select(CipherSuiteParameters parameters) {
		boolean certificateSupportChecked = false; 
		boolean certificateSupported = false;
		for (CipherSuite cipherSuite : parameters.getCipherSuites()) {
			if (cipherSuite.requiresServerCertificateMessage()) {
				if (!certificateSupportChecked){
					certificateSupported = isCertificateSupported(parameters);
				}
				if (certificateSupported) {
					if (select(cipherSuite, parameters)) {
						return true;
					}
				}
			} else if (select(cipherSuite, parameters)) {
				return true;
			}
		}
		return false;
	}
```

**Comment by sbernard31** [comment]
(I try to check which Californium version was impacted, I since this bug exist since v2.3.0)

**Comment by boaks** [comment]
The cipher suite within `selectForCertificate` is only used to check
`cipherSuite.getCertificateKeyAlgorithm() == CertificateKeyAlgorithm.EC`. That is always true, until someone extends scandium for other algorithms. Therefore the function mainly checks all (extension) parameters, and they don't vary with the cipher suite.

**Comment by boaks** [comment]
Though I work on a "mismatch-details description", I would prefer just to add more comments for the 2.6.1.

**Comment by boaks** [comment]
The other PR (master, 3.0.x) contains also unit-tests. 

`DTLSConnectorHandshakeTest.testX509HandshakeFailingNoCommonSignatureAlgorithms`

demonstrates, that the old version sticks on the `DefaultCipherSuiteSelector.checkCertificateSupport` failure and causes followup handshakes to fail as well. The bugfix in this PR fixes this bug.

**Comment by boaks** [comment]
[Fix verified also from leshan.](https://github.com/eclipse/leshan/issues/964#issuecomment-771573708)

**Pull request merged**
