### PR TITLE
Trigger onError method of message callback when the connector is shut…

### PR DESCRIPTION
**Pull request by rkimsb2**
…down.

Aimed issue #702

Signed-off-by: Rokwoon Kim <k862390@gmail.com>

### CODE REVIEW

**Comment by boaks** [comment]
FMPOV, the `void send(RawData msg)` should also call the `onError`, when running is `false`.

**Comment by rkimsb2** [comment]
To @boaks 

I changed this PR like this. Could you check this?

And.. I consider the variable running should be AtomicBoolean or not. And I think this doesn't have to be changed. Because of it's calling timing.

**Comment by rkimsb2** [comment]
Yup. I changed the message. :)

**Comment by boaks** [comment]
Thanks! 
If no objection, I would like to merge this on Monday.

**Comment by rkimsb2** [comment]
> Should we do try to have the same behavior for DTLSConnector ?

I changed void send method of DtlsConnector like this.

And about void sendMessage(RawData, DTLSSession) method, it seems already doing handles of failure.

**Pull request merged**
