### PR TITLE
Issue 1273

### PR DESCRIPTION
**Pull request by boaks**
Fix closing on uncompleted handshakes.
Add a logging-messages to analyze issue #1273.

Signed-off-by: Achim Kraus <achim.kraus@bosch.io>

### CODE REVIEW

**Comment by boaks** [comment]
@sbernard31 

I'm not sure, how much change in the logging you want for 2.2.2.
Maybe you give your preference as well.
Mainly adapting the warnings to information for drops?

**Comment by sbernard31** [comment]
I would like to integrate the log changes in the 2.2.2.
The most important to me is to be able to deactivate (in any way) drops warning logs which are "expected" without lost of "real" warning.

So we could : 
1. agree on the log level role : https://github.com/eclipse/californium/issues/1276#issuecomment-613313675
2. review and integrate : #1277
3. I can take a quick look at scandium main classes (Connector, Handshaker ...)  and propose a PR considering log level role defined (if needed).

**Comment by boaks** [comment]
And we can merge this?

**Comment by sbernard31** [comment]
yep :)

**Pull request merged**
