### PR TITLE
Add correlation context and principal to TLS connectors

### PR DESCRIPTION
**Pull request by boaks**
Extract correlation context and principal.

Signed-off-by: Achim Kraus achim.kraus@bosch-si.com

### CODE REVIEW

**Comment by boaks** [comment]
A little more than the half of the changes are new unit tests.

So @sophokles73, though @sbernard31 is busy with analysing the memory leak (see issue #429), may be you can spent some time on this PR in the next weeks :-),

**Comment by sbernard31** [comment]
I looked at this really quickly.
All of this is mainly about TCP connector which is (if I well remember) pretty experimental.
Just to say, I'm not against integrated this.

**Comment by boaks** [comment]
Yes, your right.  And the spec. seems to be still a draft.

On the other side, it only affects the TCP/TLS stuff ( I see no dependency, which affects function to change for this). So that's for me the difference to BERT, which may affect the UDP blockwise stuff and therefore that's on a separate branch.

**Comment by sbernard31** [comment]
Any reasons why this is not still not merge ?

**Comment by boaks** [comment]
I didn't want to influence other PRs. 
Currently I work on moving the rpk trust stores.
 And when I'm finished with that, then I would go to rebase and retest this and have it merged.

**Pull request merged**
