### PR TITLE
Use timestamp of add for deduplication.

### PR DESCRIPTION
**Pull request by boaks**
Fixes https://hudson.eclipse.org/californium/job/2.0.x-nightly/162/

Fixes, except the transmission of the duplicate is delayed more than TEST_EXCHANGE_LIFETIME.

Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by boaks** [comment]
If no objection, I would like to merge this soon.

**Comment by sbernard31** [comment]
@boaks, could you explain that a little more. I didn't get the point.

**Comment by boaks** [comment]
If you check the failed build, you will see, that the request was some time ago. So, if using the request time for the deduplication timeout, the deduplication doesn't apply because the second response is not longer in time. If the time of the reponse (separate CON response) is used, then the second response is in time and will be deduplicated.

**Comment by sbernard31** [comment]
OK I get it.
So the `Exchange.getNanoTimestamp()` getter is not really usefull anymore ?
And the nanoTimestamp attributes seems only needed for RTT calculation which seems not really usefull.

Do you think we could remove that ?

**Comment by boaks** [comment]
It will not save too much, so I wouldn't remove it now.

**Comment by boaks** [comment]
FMPOV `RTT` was part of the API. SO I don't see, why it should be removed,

**Comment by sbernard31** [comment]
I'm not sure to see the utility of RTT but why not.
However  for  `Exchange.getNanoTimestamp()`, it's pretty harder to see it as part of the API. It seems this was just exposed for sweep deduplicator.

**Pull request merged**
