### PR TITLE
OSCORE: update cbor to 4.0.0 and numbers to 1.4.3.

### PR DESCRIPTION
**Pull request by boaks**
Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by boaks** [comment]
@rikard-sics
@LudwigSeitz  

Please check, if it's OK for you to update the dependencies of cbor and number.

**Comment by boaks** [comment]
The lifted cose classes only depends directly from cbor, numbers is only used indirect through cbor.
This direct dependency to numbers is removed in cose in the meantime. 
And it seems that it works also for oscore to depend only indirect from numbers.
If you don't have an objection or reason to stick to a direct dependency to numbers, I would like to remove it.

**Comment by rikard-sics** [comment]
> The lifted cose classes only depends directly from cbor, numbers is only used indirect through cbor.
> This direct dependency to numbers is removed in cose in the meantime.
> And it seems that it works also for oscore to depend only indirect from numbers.
> If you don't have an objection or reason to stick to a direct dependency to numbers, I would like to remove it.

Yes, that makes sense to me. I do not foresee any issues with doing that.

**Comment by boaks** [comment]
Thanks! I wait for the related CQ to be resolved, then I will merge it.

**Comment by sophokles73** [comment]
@boaks CQs have been approved, you may proceed with checking in the changes ...

**Comment by boaks** [comment]
Thanks!

**Pull request merged**
