### PR TITLE
Split TCP implementation into own package

### PR DESCRIPTION
**Pull request by boaks**
Move TCP implementation into package element-connector-tcp to remove netty dependency from package element-connector. Then remove TCP dependency from californium-core.

Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by sbernard31** [comment]
LGTM

**Comment by sophokles73** [comment]
What about the `TcpEndpoint*` and `TlsEndpoint*` classes in *element-connector*? Shouldn't they also be moved to *element-connector-tcp*?

**Comment by boaks** [comment]
No, the idea was not to do a "perfect separation"; the TCP stuff in californium-core also still exists.
The idea was just to move the netty dependency from mandatory into optional to reduce the size of the resulting jars.

**Comment by sophokles73** [comment]
Ok, I see.

**Comment by sbernard31** [comment]
This is the same level of separation than with DTLS and coaps

**Pull request merged**
