### PR TITLE
Replace striped executor with serial executor.

### PR DESCRIPTION
**Pull request by boaks**
Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by sbernard31** [comment]
I just finished to read this refactoring.
@boaks could you remind me the purpose of this ? Did you remarks some performances benefits ?

**Comment by boaks** [comment]
Together with the executor utils (PR #728) it's about 30% faster for DTLS.
Just checkout the branch and even without the other PR, it should be faster, but I didn't measure it on its own.

**Comment by sbernard31** [comment]
I tested it using : `coaps://localhost:5784/benchmark?rlen=40 2000 1000`

### without this PR
<details>
  <summary>2000000 requests in 136712ms, 14629 reqs/s.</summary>

```
Create 2000 secure benchmark clients, expect to send 2000000 request overall to coaps://localhost:5784/benchmark?rlen=40
Benchmark clients created.
Benchmark started.
259355 requests (25935 reqs/s, 3374 retransmissions (1,30%), 0 transmission errors (0,00%), 2000 clients)
401261 requests (14190 reqs/s, 2222 retransmissions (1,57%), 0 transmission errors (0,00%), 2000 clients)
517605 requests (11634 reqs/s, 2067 retransmissions (1,78%), 0 transmission errors (0,00%), 2000 clients)
695476 requests (17787 reqs/s, 321 retransmissions (0,18%), 0 transmission errors (0,00%), 2000 clients)
835252 requests (13977 reqs/s, 1357 retransmissions (0,97%), 0 transmission errors (0,00%), 2000 clients)
998579 requests (16332 reqs/s, 502 retransmissions (0,31%), 0 transmission errors (0,00%), 2000 clients)
1154896 requests (15631 reqs/s, 93 retransmissions (0,06%), 0 transmission errors (0,00%), 2000 clients)
1325039 requests (17014 reqs/s, 200 retransmissions (0,12%), 0 transmission errors (0,00%), 2000 clients)
1463272 requests (13823 reqs/s, 778 retransmissions (0,56%), 0 transmission errors (0,00%), 2000 clients)
1614484 requests (15121 reqs/s, 0 retransmissions (0,00%), 0 transmission errors (0,00%), 2000 clients)
1773375 requests (15889 reqs/s, 1952 retransmissions (1,23%), 0 transmission errors (0,00%), 2000 clients)
1925278 requests (15190 reqs/s, 214 retransmissions (0,14%), 0 transmission errors (0,00%), 2000 clients)
2000 benchmark clients finished.
2000000 requests sent, 2000000 expected
2000000 requests in 136712ms, 14629 reqs/s
13227 retransmissions (0,66%)
  1 clients with 754 requests.
 15 clients with 761 to 799 requests.
 77 clients with 801 to 839 requests.
194 clients with 841 to 879 requests.
268 clients with 880 to 919 requests.
315 clients with 920 to 959 requests.
279 clients with 960 to 999 requests.
212 clients with 1000 to 1039 requests.
173 clients with 1040 to 1079 requests.
151 clients with 1080 to 1119 requests.
102 clients with 1120 to 1159 requests.
 82 clients with 1160 to 1199 requests.
 41 clients with 1201 to 1237 requests.
 29 clients with 1242 to 1278 requests.
 25 clients with 1281 to 1319 requests.
 10 clients with 1321 to 1351 requests.
 16 clients with 1360 to 1395 requests.
  4 clients with 1401 to 1436 requests.
  3 clients with 1441 to 1470 requests.
  2 clients with 1490 to 1493 requests.
  1 clients with 1536 requests.
17:51:22.586 WARN [DTLSConnector]: Shutdown DTLS connector on [0.0.0.0/0.0.0.0:54896] not terminated in time!
17:51:22.583 WARN [DTLSConnector]: Shutdown DTLS connector on [0.0.0.0/0.0.0.0:45153] not terminated in time!
17:51:22.586 WARN [DTLSConnector]: Shutdown DTLS connector on [0.0.0.0/0.0.0.0:50839] not terminated in time!
17:51:22.586 WARN [DTLSConnector]: Shutdown DTLS connector on [0.0.0.0/0.0.0.0:46395] not terminated in time!
```
</details> 
<details>
  <summary>2000000 requests in 135236ms, 14788 reqs/s.</summary>

```
Create 2000 secure benchmark clients, expect to send 2000000 request overall to coaps://localhost:5784/benchmark?rlen=40
Benchmark clients created.
Benchmark started.
324418 requests (32441 reqs/s, 2938 retransmissions (0,91%), 0 transmission errors (0,00%), 2000 clients)
469152 requests (14473 reqs/s, 414 retransmissions (0,29%), 0 transmission errors (0,00%), 2000 clients)
587552 requests (11840 reqs/s, 2083 retransmissions (1,76%), 0 transmission errors (0,00%), 2000 clients)
766759 requests (17920 reqs/s, 339 retransmissions (0,19%), 0 transmission errors (0,00%), 2000 clients)
903620 requests (13686 reqs/s, 824 retransmissions (0,60%), 0 transmission errors (0,00%), 2000 clients)
1040425 requests (13680 reqs/s, 0 retransmissions (0,00%), 0 transmission errors (0,00%), 2000 clients)
1222944 requests (18251 reqs/s, 370 retransmissions (0,20%), 0 transmission errors (0,00%), 2000 clients)
1362260 requests (13931 reqs/s, 1079 retransmissions (0,77%), 0 transmission errors (0,00%), 2000 clients)
1538343 requests (17608 reqs/s, 143 retransmissions (0,08%), 0 transmission errors (0,00%), 2000 clients)
1681943 requests (14360 reqs/s, 466 retransmissions (0,32%), 0 transmission errors (0,00%), 2000 clients)
1861213 requests (17927 reqs/s, 51 retransmissions (0,03%), 0 transmission errors (0,00%), 2000 clients)
2000 benchmark clients finished.
2000000 requests sent, 2000000 expected
2000000 requests in 135236ms, 14788 reqs/s
9023 retransmissions (0,45%)
  1 clients with 770 requests.
 19 clients with 800 to 838 requests.
 98 clients with 840 to 879 requests.
285 clients with 880 to 919 requests.
425 clients with 920 to 959 requests.
429 clients with 960 to 999 requests.
257 clients with 1000 to 1039 requests.
152 clients with 1040 to 1079 requests.
 86 clients with 1080 to 1119 requests.
 56 clients with 1120 to 1159 requests.
 41 clients with 1160 to 1199 requests.
 47 clients with 1200 to 1237 requests.
 33 clients with 1241 to 1277 requests.
 39 clients with 1280 to 1318 requests.
 19 clients with 1325 to 1358 requests.
  8 clients with 1373 to 1397 requests.
  2 clients with 1487 to 1507 requests.
  2 clients with 1543 to 1558 requests.
  1 clients with 1616 requests.
17:45:01.719 WARN [DTLSConnector]: Shutdown DTLS connector on [0.0.0.0/0.0.0.0:42482] not terminated in time!
17:45:01.716 WARN [DTLSConnector]: Shutdown DTLS connector on [0.0.0.0/0.0.0.0:43289] not terminated in time!
17:45:01.716 WARN [DTLSConnector]: Shutdown DTLS connector on [0.0.0.0/0.0.0.0:47205] not terminated in time!
17:45:01.716 WARN [DTLSConnector]: Shutdown DTLS connector on [0.0.0.0/0.0.0.0:47477] not terminated in time!

```
</details>    
    
 
### with this PR :
<details>
  <summary>2000000 requests in 139285ms, 14359 reqs/s.</summary>

```
reate 2000 secure benchmark clients, expect to send 2000000 request overall to coaps://localhost:5784/benchmark?rlen=40
Benchmark clients created.
Benchmark started.
261017 requests (26101 reqs/s, 3275 retransmissions (1,25%), 0 transmission errors (0,00%), 2000 clients)
404598 requests (14358 reqs/s, 2074 retransmissions (1,44%), 0 transmission errors (0,00%), 2000 clients)
530390 requests (12579 reqs/s, 1988 retransmissions (1,58%), 0 transmission errors (0,00%), 2000 clients)
688061 requests (15767 reqs/s, 147 retransmissions (0,09%), 0 transmission errors (0,00%), 2000 clients)
853320 requests (16525 reqs/s, 933 retransmissions (0,56%), 0 transmission errors (0,00%), 2000 clients)
998123 requests (14480 reqs/s, 612 retransmissions (0,42%), 0 transmission errors (0,00%), 2000 clients)
1129659 requests (13153 reqs/s, 1012 retransmissions (0,77%), 0 transmission errors (0,00%), 2000 clients)
1281519 requests (15186 reqs/s, 342 retransmissions (0,23%), 0 transmission errors (0,00%), 2000 clients)
1425999 requests (14448 reqs/s, 59 retransmissions (0,04%), 0 transmission errors (0,00%), 2000 clients)
1575308 requests (14930 reqs/s, 610 retransmissions (0,41%), 0 transmission errors (0,00%), 2000 clients)
1727346 requests (15203 reqs/s, 756 retransmissions (0,50%), 0 transmission errors (0,00%), 2000 clients)
1869967 requests (14262 reqs/s, 898 retransmissions (0,63%), 0 transmission errors (0,00%), 2000 clients)
2000 benchmark clients finished.
17:39:39.131 ERROR [BenchmarkClient]: failed after 1428 requests!
17:39:39.136 ERROR [ReliabilityLayer]: Exception for Exchange[L2000245, complete] in MessageObserver: connector must be started before sending messages is possible
java.lang.IllegalStateException: connector must be started before sending messages is possible
	at org.eclipse.californium.scandium.DTLSConnector.send(DTLSConnector.java:1349)
	at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendRequest(CoapEndpoint.java:741)
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackBottomAdapter.sendRequest(BaseCoapStack.java:187)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer.sendRequest(ReliabilityLayer.java:108)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer$1.retransmit(ReliabilityLayer.java:104)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer$RetransmissionTask.retry(ReliabilityLayer.java:448)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer$RetransmissionTask.access$0(ReliabilityLayer.java:405)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer$RetransmissionTask$1.run(ReliabilityLayer.java:400)
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:272)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2000000 requests sent, 2000000 expected
2000000 requests in 139285ms, 14359 reqs/s
12763 retransmissions (0,64%)
  3 clients with 667 to 671 requests.
  4 clients with 681 to 707 requests.
  5 clients with 725 to 756 requests.
  5 clients with 766 to 796 requests.
 51 clients with 801 to 839 requests.
109 clients with 840 to 879 requests.
188 clients with 880 to 919 requests.
315 clients with 920 to 959 requests.
407 clients with 960 to 999 requests.
355 clients with 1000 to 1039 requests.
237 clients with 1040 to 1079 requests.
118 clients with 1080 to 1119 requests.
 68 clients with 1120 to 1157 requests.
 46 clients with 1160 to 1198 requests.
 39 clients with 1200 to 1237 requests.
 21 clients with 1240 to 1277 requests.
 14 clients with 1283 to 1312 requests.
  5 clients with 1320 to 1353 requests.
  4 clients with 1364 to 1379 requests.
  1 clients with 1428 requests.
  1 clients with 1456 requests.
  1 clients with 1502 requests.
  3 clients with 1769 to 1794 requests.
```
</details> 
<details>
  <summary>2000000 requests in 141808ms, 14103 reqs/s</summary>

```
Create 2000 secure benchmark clients, expect to send 2000000 request overall to coaps://localhost:5784/benchmark?rlen=40
Benchmark clients created.
Benchmark started.
275591 requests (27559 reqs/s, 3930 retransmissions (1,43%), 0 transmission errors (0,00%), 2000 clients)
401129 requests (12553 reqs/s, 2563 retransmissions (2,04%), 0 transmission errors (0,00%), 2000 clients)
518471 requests (11734 reqs/s, 1987 retransmissions (1,69%), 0 transmission errors (0,00%), 2000 clients)
680688 requests (16221 reqs/s, 666 retransmissions (0,41%), 0 transmission errors (0,00%), 2000 clients)
832431 requests (15174 reqs/s, 594 retransmissions (0,39%), 0 transmission errors (0,00%), 2000 clients)
971347 requests (13891 reqs/s, 1547 retransmissions (1,11%), 0 transmission errors (0,00%), 2000 clients)
1117028 requests (14568 reqs/s, 692 retransmissions (0,48%), 0 transmission errors (0,00%), 2000 clients)
1257717 requests (14068 reqs/s, 707 retransmissions (0,50%), 0 transmission errors (0,00%), 2000 clients)
1415564 requests (15784 reqs/s, 118 retransmissions (0,07%), 0 transmission errors (0,00%), 2000 clients)
1553278 requests (13771 reqs/s, 810 retransmissions (0,59%), 0 transmission errors (0,00%), 2000 clients)
1690631 requests (13735 reqs/s, 591 retransmissions (0,43%), 0 transmission errors (0,00%), 2000 clients)
1860410 requests (16977 reqs/s, 1334 retransmissions (0,79%), 0 transmission errors (0,00%), 2000 clients)
2000 benchmark clients finished.
17:54:51.351 ERROR [BenchmarkClient]: failed after 1371 requests!
17:54:51.355 ERROR [ReliabilityLayer]: Exception for Exchange[L2000923, complete] in MessageObserver: connector must be started before sending messages is possible
java.lang.IllegalStateException: connector must be started before sending messages is possible
	at org.eclipse.californium.scandium.DTLSConnector.send(DTLSConnector.java:1349)
	at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendRequest(CoapEndpoint.java:741)
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackBottomAdapter.sendRequest(BaseCoapStack.java:187)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer.sendRequest(ReliabilityLayer.java:108)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer$1.retransmit(ReliabilityLayer.java:104)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer$RetransmissionTask.retry(ReliabilityLayer.java:448)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer$RetransmissionTask.access$0(ReliabilityLayer.java:405)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer$RetransmissionTask$1.run(ReliabilityLayer.java:400)
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:272)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2000000 requests sent, 2000000 expected
2000000 requests in 141808ms, 14103 reqs/s
16045 retransmissions (0,80%)
  1 clients with 635 requests.
  1 clients with 676 requests.
  7 clients with 685 to 714 requests.
  2 clients with 733 to 740 requests.
  6 clients with 763 to 799 requests.
 36 clients with 806 to 839 requests.
172 clients with 840 to 879 requests.
321 clients with 880 to 919 requests.
331 clients with 920 to 959 requests.
241 clients with 960 to 999 requests.
206 clients with 1000 to 1039 requests.
200 clients with 1040 to 1079 requests.
179 clients with 1080 to 1119 requests.
108 clients with 1120 to 1159 requests.
 77 clients with 1160 to 1198 requests.
 40 clients with 1200 to 1239 requests.
 26 clients with 1240 to 1279 requests.
 22 clients with 1280 to 1318 requests.
 19 clients with 1320 to 1356 requests.
  3 clients with 1364 to 1388 requests.
  1 clients with 1406 requests.
  1 clients with 1454 requests.
```
</details>  
   

There is an illegalStateException with this PR and lot of warning (not terminated in time!) at this end of the tests.

**Comment by boaks** [comment]
My results:

coaps://localhost:5784/benchmark?rlen=40 500 1000

Without:
500000 requests in 19673ms, 25415 reqs/s

With:
500000 requests in 17327ms, 28856 reqs/s
117 retransmissions (0,02%)

coap://localhost:5784/benchmark?rlen=40 500 1000

Without:
1000000 requests in 18501ms, 54051 reqs/s
1648 retransmissions (0,16%)

With:
1000000 requests in 15691ms, 63730 reqs/s
1467 retransmissions (0,15%)

On my system, I let the server run and start the benchmark twice, the second run is mostly faster. It's also important to have either enough heap or an other deduplicator (I use -d64 -Xmx8g -XX:+UseG1GC).

I can't start more client without the executor optimization of the other PR.
My "final" version uses the optimized executor and multiple receiver threads.
But thought you want the smaller PRs, I isolated this replacement.
The changes are mostly effect the start/stop therefore it's hard to present them in parallel and therefore their either already merged together or a few parallel.

**Comment by boaks** [comment]
> There is an illegalStateException with this PR 
Unit test or benchmarks?

> and lot of warning (not terminated in time!) at this end of the tests without this PR.
Unit test or benchmarks?

**Comment by boaks** [comment]
> java.lang.IllegalStateException: connector must be started before sending messages is possible
> 	at org.eclipse.californium.scandium.DTLSConnector.send(DTLSConnector.java:1383)
> 	at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendRequest(CoapEndpoint.java:726)
> 

According your comment 
https://github.com/eclipse/californium/pull/699#discussion_r208567250 ,

"This kind of modification is not really linked to executor modifications ?"

this must be fixed in an other PR :-).

**Comment by boaks** [comment]
More benchmarks with PR #728 applied also:

coap:
1000000 requests in 14511 ms, 68913 reqs/s
1045 retransmissions (0,10%)

coaps:
500000 requests in 13643 ms, 36648 reqs/s
653 retransmissions (0,13%)

(The coaps speedup results may be caused more by the improvement on the client side.)

**Comment by boaks** [comment]
With the last benchmark from yesterday I got aware, that testing on linux uses only 1 sender and 1 receiver thread. Using the branch "all_executor_optimizations" and removing all Californium?.properties to setup the new defaults results in #processor sender threads and #processors/2 receiver threads for the benchmark server. I repeated the first benchmark also with that multi-thread setup:

without this PR:
coap:
1000000 requests in 20827ms, 48014 reqs/s
1661 retransmissions (0,17%)
coaps:
500000 requests in 15392ms, 32484 reqs/s
1364 retransmissions (0,27%)

with this PR:
coap:
1000000 requests in 16084ms, 62173 reqs/s
1371 retransmissions (0,14%)
coaps
500000 requests in 10914ms, 45812 reqs/s
670 retransmissions (0,13%)

coap: 29%
coaps: 41%

**Comment by sbernard31** [comment]
I rebench (coaps://localhost:5784/benchmark?rlen=40 500 1000) a bit using you advice.

(removing californium.properties and running twice and using -d64 -Xmx8g -XX:+UseG1GC)

Without this PR : 
500000 requests in 32589ms, 15342 reqs/s
1305 retransmissions (0,26%)
500000 requests in 31668ms, 15788 reqs/s
753 retransmissions (0,15%)

With this PR : 
500000 requests in 37202ms, 13440 reqs/s
1713 retransmissions (0,34%)
500000 requests in 36361ms, 13750 reqs/s
1443 retransmissions (0,29%)

After the bench I also give a try with visualvm to look at memory/cpu consumption and it seems a bit higher with this PR. (especially memory which go up to ~2500MB againt ~2000MB) I'm aware this is not a precise metrics, so I just share this as a hint.

**Comment by sbernard31** [comment]
### Same bench with : all_executor_optimizations

500000 requests in 24576 ms, 20345 reqs/s
1208 retransmissions (0,24%)
500000 requests in 22197 ms, 22525 reqs/s
905 retransmissions (0,18%)

### Same bench with only #728 :

500000 requests in 25181 ms, 19856 reqs/s
1381 retransmissions (0,28%)
500000 requests in 25660 ms, 19485 reqs/s
1266 retransmissions (0,25%)

**Comment by boaks** [comment]
I have no explanation, why you got different results :-).
But, I'm unfortunately also not able to spent more time in to this issue.
I spent a lot of days in make it "all together working". I you want to find put, if the step on their own have benefits, just do it..

My target: is to reach the "all_executor_optimizations".
- remove the striped execution
- make it possible to use executors more general (all but currently not for receive threads).
   Especially to be able to create more clients per process.
- use multiple receive thread also for DTLS to leave it to the user to find out, what fits best.

About the heap: 
maybe you disable the deduplicator using "NO_DEDUPLICATOR" and see, if this changes the heap uisage. From my experience, the deduplicator require more memory as more request per seconds are deduplicated by it (currently it keep all request for about 24,7 s, therefore, as more you send, the more heap is required.)

**Comment by sbernard31** [comment]
@boaks, I understand and if you think this will behave better,  let's give a try by integrating all this.

**Pull request merged**
