### PR TITLE
Add javadoc about IPv6 and multiaddress interfaces.

### PR DESCRIPTION
**Pull request by boaks**
Issue #315

Signed-off-by: Achim Kraus <achim.kraus@bosch.io>

### CODE REVIEW

**Review by CiaranWoodward — COMMENTED** [review]
Looks good, thanks for putting this together! I would suggest a slight change of wording, but otherwise I think this solves the issue as well as is practical to do right now.

Suggestion:
```
 * Note: using IPv6 interfaces with multiple addresses including permanent and
 * temporary (with potentially several different prefixes) currently causes
 * issues on the server side. The outgoing traffic in response to incoming may
 * select a different src address than the incoming dst address. To overcome this,
 * please ensure that the 'any address' is not used on the server side and a separate
 * CoapEndpoint is created for each address to receive incoming traffic.
```

**Comment by boaks** [comment]
Adapted according your proposal.

**Review by CiaranWoodward — APPROVED** [review]
Looks good to me, thanks!

**Comment by boaks** [comment]
Thanks for your feedback!

**Pull request merged**
