### PR TITLE
Add unix health logger based on netstat.

### PR DESCRIPTION
**Pull request by boaks**
Read /proc/net/snmp to access udp diagnose statistics from OS.

Signed-off-by: Achim Kraus <achim.kraus@bosch.io>

### CODE REVIEW

**Comment by boaks** [comment]
> (By the way for command line : my first impression of https://picocli.info/ was really good)

Maybe I missed something, but, I wouldn't name a 360K library "pico" :-).

**Comment by sbernard31** [comment]
I agree :D

Last time I take a look it was more arround 250K. This is still very fat :D.

But for demo or server I think it's OK

**Comment by boaks** [comment]
> But for demo or server I think it's OK

That's right.

**Comment by boaks** [comment]
What's about just use "commons-cli" as leshan?

**Comment by sbernard31** [comment]
It's another possibility.

I tested both and my personal preference goes to **picocli** if you don't care so much about library size:
- easier to use,
- could also be used with jline to create some interactive command,
- support color.

If I would had time, I would have migrated to it for the 1.0.0. I will maybe do it later. (https://github.com/eclipse/leshan/issues/569)

**Pull request merged**
