### PR TITLE
Preserve session creation time.

### PR DESCRIPTION
**Pull request by boaks**
Adjust time on setting master-secret.

Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by sbernard31** [comment]
Could you explain the purpose of this ? :)

**Comment by boaks** [comment]
Enable custom implementation, which use the session create time to "expire" session tickets or sessions.
And I want to display the session creation time, when I use the client session cache extension on my clients.

**Comment by sbernard31** [comment]
Ok, Why creationTime should be adjusted on setting master-secret  ?

**Comment by boaks** [comment]
Because, if a client tries the resume a session, but ends up in a full handshake, I want to update the time. FMPOV the security level is based on timespan of the master-secret.

**Comment by sbernard31** [comment]
OK, it makes sense !
It can be merged.

**Pull request merged**
