### PR TITLE
Coap health logger

### PR DESCRIPTION
**Pull request by boaks**
Signed-off-by: Achim Kraus achim.kraus@bosch-si.com

### CODE REVIEW

**Comment by sbernard31** [comment]
You need this when you run "bench" tests ? and for junit ?

**Comment by boaks** [comment]
> You need this when you run "bench" tests ?

Mainly for that. But lets first work on the other stuff get merged.

**Comment by boaks** [comment]
If I use that library, and have the complete usage under control, it's possible to externalize this.

From inside, it's not hat easy. For debugging I usually like "simple and direct implementations", but I will check, if I can reduce the impact, if not used.

**Comment by boaks** [comment]
withdrawn for PR #1130

**Pull request closed without merging**
