### PR TITLE
Test stop dtls

### PR DESCRIPTION
**Pull request by boaks**
Add tests for start and stop the dtls connector.
Fix issue #702 and #712 

Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by boaks** [comment]
I work on the renew of this PR ;-(.

Double synchronization in `stop`, and I understand the striped `shutdown` more now, and so I work on a better fix. 
I also changed the ConnectionStore remove from "using the parameter type to remove the session from the session cache or not". to using an additional method with an explicit parameter to remove it from the session cache. 

> Double synchronization in stop

That's also somehow the result of changing the same stuff over too long time again and again ... it makes blind. (`stop` was also adapted in PR #699).

@sbernard31
Should we make a next milestone release without PR #699?  
Or would it be OK to include PR #699 soon, before the next milestone?

**Comment by boaks** [comment]
New version:
- cleaner StripedExecutorService fix.
- cleaner ResumptionSupportingConnectionStore fix/API
- more rare exceptions fixed.

**Comment by sbernard31** [comment]
> cleaner StripedExecutorService fix.

I'm not sure to understand the fix,  but If you think this is an improvement you could consider to contribute it to https://github.com/kabutz/javaspecialists/tree/master/src/main/java/eu/javaspecialists/tjsn/concurrency/stripedexecutor
There is also some tests in this repo, maybe you could check your modification with it : https://github.com/kabutz/javaspecialists/tree/master/src/test/java/eu/javaspecialists/tjsn/concurrency/stripedexecutor

**Comment by boaks** [comment]
My plan is to remove the `StripedExecutorService`, this fix should only help temporary to overcome the error occurred when executing the jobs returned by `shutdownNow`.

I run that test

https://github.com/kabutz/javaspecialists/tree/master/src/test/java/eu/javaspecialists/tjsn/concurrency/stripedexecutor

successfully. These test don't execute the returned jobs, therefore they don't show the defect.
The wrapper jobs created in `SerialExecutor.execute()` removes that executor, when its serial job queue `tasks` is empty. In `shutdownNow` the `tasks` are taken, therefore each wrapper job now tries to remove the `SerialExecutor`, but only the first could do this successful.

**Comment by boaks** [comment]
Left notice in source project.
https://github.com/kabutz/javaspecialists/issues/2

**Comment by sbernard31** [comment]
> My plan is to remove the StripedExecutorService

what do you plan to use instead ?

**Comment by boaks** [comment]
I've tested a prototype, where the SerialExecutor is the Exchange and the serial tasks queue is implemented in the Exchange. This obsoletes the stipes map and the more frequently temporary serial tasks queues. If I can spent more time in it, I would generalize it and use it for scandium also. But I guess, is quite some time in the future :-). 

Therefore the fix, but I also don't want to spend too much time in it.

**Comment by boaks** [comment]
I will merge this latest on Monday. 
I don't see that benefit in waiting for the feedback for
https://github.com/kabutz/javaspecialists/issues/2
especially, because this PR overlaps #699.

If we got other feedback from the `StripedExecutorService` origin, we can update it again :-)

**Pull request merged**
