### PR TITLE
Add argument for custom coap stack.

### PR DESCRIPTION
**Pull request by boaks**
Issue #990
Replace HashMapCtxDB singleton by the introduced argument.

Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by boaks** [comment]
@rikard-sics
@LudwigSeitz 

Please feel free to comment, and, if possible, check, if these changes works for you.
I added a default ctx db to the factory and a custom stack argument to the CoapEndpoint.Builder.

**Comment by rikard-sics** [comment]
Yes that looks like it should work for me. Then it is the responsibility of the application to create the context DB (which it could for instance create as a singleton) and set it when setting the default CoAP stack factory with OSCoreCoapStackFactory.useAsDefault(db). It is also possible to use multiple context DB:s and specify which one to use when building a CoapEndpoint.

Some thoughts I had.
1. For the context re-derivation functionality I was planning some changes so the client can set a flag in the actual context to indicate it should be re-derived. I already have some flags in the context like includeContextId (include the context id in messages generated using this context). I will make a PR for this and using the approach you suggested with an asynchronous client sending the re-derivation message.

2. I know Ludwig is using this code in some work he is doing where he needs to retrieve contexts in various situations. Hopefully this approach will work for his use case.

3. Should it be possible to retrieve the currently set default context DB from the OSCoreCoapStackFactory? For instance OSCoreCoapStackFactory.getDefaultCtxDb() which can return the value of defaultCtxDb?

**Comment by boaks** [comment]
2. and 3.

In my opinion, if the application requires access to the  context DB, it's totally OK, if the application provides a separate application level singleton approach. Doing so obsoletes the access to the default context db of the factory. Currently the default of the factory could be changed (due to the requirements of the unit tests), so accessing it may lead to unexpected things.

**Comment by rikard-sics** [comment]
>     1. and 3.
> 
> 
> In my opinion, if the application requires access to the context DB, it's totally OK, if the application provides a separate application level singleton approach. Doing so obsoletes the access to the default context db of the factory. Currently the default of the factory could be changed (due to the requirements of the unit tests), so accessing it may lead to unexpected things.

Alright, also hopefully the implementation of the OSCORE peer identity will help in Ludwig's case so he does not need access to the context DB as much.

**Pull request merged**
