### PR TITLE
Keep closed session and mark the closed receive window.

### PR DESCRIPTION
**Pull request by boaks**
Signed-off-by: Achim Kraus <achim.kraus@bosch.io>

### CODE REVIEW

**Comment by boaks** [comment]
A "cheap cheat", not CLOSE, just mark the session with the record_sequence_number. Drop messages after that number, process messages before that number.

**Comment by sbernard31** [comment]
I looked at this and I understand the idea. (I think it should work)
But I have some concern about some part of the code where connection could be retrieved and not active. (like maybe where we raise `EndpointUnconnectedException` like `DTLSConnector.send(RawData)`)

**Comment by boaks** [comment]
For incoming, the records should be stopped by "session.isRecordProcessable" (small fix for session == null is on the way).
For outgoing, the difference maybe, that with this, a resumption is tried, with the other a full handshake. I think, the resumption is not too bad. Or do you see something, I oversee?

**Comment by sbernard31** [comment]
I read the code quickly again and you're right it should be OK.

(Just a detail but first time I read the code, "closing a session" sounds strange to me because as I understand the rfc a session can not be closed, this is the connection which is closed. I think the issue here is that our Connection / Session object does not really match the connection/session concept of the RFC)

**Comment by boaks** [comment]
> Just a detail 

you're right :-).

**Comment by boaks** [comment]
I added test, redesigned it a little, and deprecated the obsolete `CloseSupportingConnectionStore`.

**Pull request merged**
