### PR TITLE
Revapi ignores 

### PR DESCRIPTION
**Pull request by boaks**
Fix inconsistent API scopes.
Add "api-changes.json" to ignore APIfixes.
Skip revapi for module cf-pubsub, not deployed for 2.0.0.

Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by sbernard31** [comment]
Please do what you want about that.

**Comment by sbernard31** [comment]
Reading again my previous comment, and sounds a bit aggressive :worried: : 
I meant I have no strong opinion about that so if you think this is the right way, go for this.
(more details [here](https://github.com/eclipse/californium/issues/1166#issuecomment-566024894))

(just in case I open an issue about that at [revapi github](https://github.com/revapi/revapi/issues/created_by/sbernard31))

**Comment by boaks** [comment]
So, start to go for PR #1168 and then this, and afterwards adjust the other pending PR's accordingly?

**Comment by sbernard31** [comment]
Just to be sure I was talking about the "Non-Public Part of API" inconsistency.

What does it mean : "adjust the other pending PR's accordingly?"

**Comment by boaks** [comment]
Either try to add changes to api-ignore or try to not change the API.
FMPOV, it's much more important to change it according a good future solution then to keep a (not used) API for "strict technical compatibility".

**Comment by boaks** [comment]
Just to mention:
Agree on these two PRs, doesn't mean to agree on the other PRs, even if the get adapted. It's more like, these two are the minimal consensus, the rest maybe discussion.

**Comment by sbernard31** [comment]
So I agree on this PR and #1168.

For the rest, I would like to know  your opinion about https://github.com/eclipse/californium/pull/1168#issuecomment-566027052 ?

**Pull request merged**
