### PR TITLE
Bugfix cancel observe relation

### PR DESCRIPTION
**Pull request by boaks**
Fixes bugs.eclipse.org #475810.
Provides also unit tests to show the defect.

Signed-off-by: Achim Kraus achim.kraus@bosch-si.com

### CODE REVIEW

**Comment by mkovatsc** [comment]
This pull request also introduces a feature, that is, setting a custom observe manager. Is this only for the tests or is there more to it?

**Comment by boaks** [comment]
The second commit is only for testing. I'm not sure, if the additional test should be merged. Therefore I put them in a second commit.

**Comment by mkovatsc** [comment]
Hmm, apparently the comments from yesterday did not make it...
Could you set the HEAD to b5e75cd, that is, dismiss the last commit? It opens up configuration that should not be there.

**Comment by boaks** [comment]
Remove the commit with the "test only extensions".

**Pull request merged**
