### PR TITLE
ClientAsynchronousTest rewritten

### PR DESCRIPTION
**Pull request by mojadita**
ClientAsynchronousTest does all assertions in the callback routine, that
doesn't get called in case of absent server.  I have tried to run it
from eclipse, and got completely surprised on seeing it pass, when eclipse was
still asking for permissions to open the udp listening
socket of the server.

I have rewritten this tests to only make response available and properly
wait for the response to arrive, and give a complete test timeout of 5s.
So, in case of failing server the test does not pass.

Signed-off-by: Luis Colorado <lcu@basen.net>

### CODE REVIEW

**Comment by sophokles73** [comment]
I think this PR is obsolete after the changes I have pushed today.
@mojadita, can you check and maybe close this PR?

**Comment by mojadita** [comment]
Well, but you have already closed the PR... I don't feel confortable this way.... sorry.

**Comment by sophokles73** [comment]
Sorry for the inconvenience, I had the changes to the tests in the drawer for some time now and wanted to finish them before master diverged too much.

**Comment by mojadita** [comment]
Well, I'll close this pull request, after checking your code, I don't find any significative differences between your approach and mine.

**Pull request closed without merging**
