### PR TITLE
Add Android API level compatibility check to build (using level 19)

### PR DESCRIPTION
**Pull request by sbernard31**
Using [animal-sniffer-maven-plugin](http://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/) and [android signatures](https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22net.sf.androidscents.signature%22), it is possible to ensure compatibility with a given android API level.

### CODE REVIEW

**Comment by boaks** [comment]
Did you check, if eclipse jenkins can process these pom changes?

**Comment by sbernard31** [comment]
Good question I will check that.

**Comment by sbernard31** [comment]
`versions-maven-plugin` seems to say it's ok, but I could make a real tests on jenkins instance tomorrow.

**Comment by sbernard31** [comment]
I create a [`californium-dry-run`](https://hudson.eclipse.org/californium/job/californium-dry-run/) job and check my branch.
It seems ok : 
https://hudson.eclipse.org/californium/job/californium-dry-run/1/consoleFull

**Comment by boaks** [comment]
sounds good, LGTM

**Pull request merged**
