### PR TITLE
Fix 451

### PR DESCRIPTION
**Pull request by boaks**
#451

Add unit test for timedout blockwise notify (also correcting a config type).
Ignore timeout for blockwise notifies.

Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by boaks** [comment]
@sbernard31 
I would like to merge this, but this will raise a conflict with your PR #449.
The conflict should be easy to solve.

**Comment by sbernard31** [comment]
```java
    @Override
    public void onCancel() {
        failed();
    }

    @Override
    protected void failed() {
         observationStore.remove(request.getToken());
         exchangeStore.releaseToken(idByToken);
    }
```
On notification I think we don't want to remove observation or release token at all ?

**Comment by boaks** [comment]
> On notification I think we don't want to remove observation or release token at all ?

I don't know (or at least, I'm very unsure). Therefore I only changed the case, which caused an error.

**Comment by sbernard31** [comment]
E.g. on a block2 notification, the client try to send a GET with block2 option  but it fails onSendError()
This will cancel the observation. I don't think this is what we want.

**Comment by boaks** [comment]
My only intention is to fix #451. And the scope of this PR is exactly that. issue 
For additional fixes, feel free to add them.

**Comment by sbernard31** [comment]
OK ... so LGTM ...

**Pull request merged**
