### PR TITLE
 Stop cleaning task when we clear a block (fix for #537) 

### LINKED ISSUE #537: Unexpected 4.08 Request Entity Incomplete reponse with block1
We faced this kind of error after a while using block1 with same IP/port same URI with cf 2.0.0-M6 (reproducible with 2.0.0-M7).

See capture here : 
```
     27 17.921800      64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     104    ACK, MID:3915, 2.31 Continue, TKN:4b 0f 74 b1, Block #0, /push
     28 17.923302      2001:569:6ff9:6647:7520:b874:b77:b628 64:ff9b::3411:8e3e    56830    5686     CoAP     163    CON, MID:3916, POST, TKN:4c 0f 75 b1, End of Block #1, /push?ep=351711090003168
     29 18.177398      64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     104    ACK, MID:3916, 2.01 Created, TKN:4c 0f 75 b1, End of Block #1, /push
     30 22.460344      2001:569:6ff9:6647:7520:b874:b77:b628 64:ff9b::3411:8e3e    56830    5686     CoAP     260    CON, MID:3917, POST, TKN:4d 0f 79 b1, Block #0, /push?ep=351711090003168
     31 22.682601      64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     104    ACK, MID:3917, 2.31 Continue, TKN:4d 0f 79 b1, Block #0, /push
     32 22.683741      2001:569:6ff9:6647:7520:b874:b77:b628 64:ff9b::3411:8e3e    56830    5686     CoAP     163    CON, MID:3918, POST, TKN:4e 0f 79 b1, End of Block #1, /push?ep=351711090003168
     33 22.958042      64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     104    ACK, MID:3918, 2.01 Created, TKN:4e 0f 79 b1, End of Block #1, /push
     34 27.459536      2001:569:6ff9:6647:7520:b874:b77:b628 64:ff9b::3411:8e3e    56830    5686     CoAP     260    CON, MID:3919, POST, TKN:4f 0f 7e b1, Block #0, /push?ep=351711090003168
     35 27.717607      64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     104    ACK, MID:3919, 2.31 Continue, TKN:4f 0f 7e b1, Block #0, /push
     36 27.718688      2001:569:6ff9:6647:7520:b874:b77:b628 64:ff9b::3411:8e3e    56830    5686     CoAP     162    CON, MID:3920, POST, TKN:50 0f 7e b1, End of Block #1, /push?ep=351711090003168
     37 27.977879      64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     104    ACK, MID:3920, 2.01 Created, TKN:50 0f 7e b1, End of Block #1, /push
     38 32.461906      2001:569:6ff9:6647:7520:b874:b77:b628 64:ff9b::3411:8e3e    56830    5686     CoAP     260    CON, MID:3921, POST, TKN:51 0f 83 b1, Block #0, /push?ep=351711090003168
     39 32.719572      64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     104    ACK, MID:3921, 2.31 Continue, TKN:51 0f 83 b1, Block #0, /push
     40 32.720789      2001:569:6ff9:6647:7520:b874:b77:b628 64:ff9b::3411:8e3e    56830    5686     CoAP     163    CON, MID:3922, POST, TKN:52 0f 83 b1, End of Block #1, /push?ep=351711090003168
     41 32.997208      64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     104    ACK, MID:3922, 2.01 Created, TKN:52 0f 83 b1, End of Block #1, /push
.... .... ... ~ 5 minutes later ... ... ...
    270 322.459758     2001:569:6ff9:6647:7520:b874:b77:b628 64:ff9b::3411:8e3e    56830    5686     CoAP     260    CON, MID:4037, POST, TKN:c5 0f a5 b2, Block #0, /push?ep=351711090003168
    271 322.718599     64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     104    ACK, MID:4037, 2.31 Continue, TKN:c5 0f a5 b2, Block #0, /push
    272 322.719724     2001:569:6ff9:6647:7520:b874:b77:b628 64:ff9b::3411:8e3e    56830    5686     CoAP     163    CON, MID:4038, POST, TKN:c6 0f a5 b2, End of Block #1, /push?ep=351711090003168
    273 322.936894     64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     123    ACK, MID:4038, 4.08 Request Entity Incomplete, TKN:c6 0f a5 b2, End of Block #1, /push (text/plain)
    274 327.460062     2001:569:6ff9:6647:7520:b874:b77:b628 64:ff9b::3411:8e3e    56830    5686     CoAP     260    CON, MID:4039, POST, TKN:c7 0f aa b2, Block #0, /push?ep=351711090003168
    275 327.698077     64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     104    ACK, MID:4039, 2.31 Continue, TKN:c7 0f aa b2, Block #0, /push
    276 327.699454     2001:569:6ff9:6647:7520:b874:b77:b628 64:ff9b::3411:8e3e    56830    5686     CoAP     164    CON, MID:4040, POST, TKN:c8 0f aa b2, End of Block #1, /push?ep=351711090003168
    277 327.961424     64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     104    ACK, MID:4040, 2.01 Created, TKN:c8 0f aa b2, End of Block #1, /push
    278 332.461631     2001:569:6ff9:6647:7520:b874:b77:b628 64:ff9b::3411:8e3e    56830    5686     CoAP     260    CON, MID:4041, POST, TKN:c9 0f af b2, Block #0, /push?ep=351711090003168
    279 332.698640     64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     104    ACK, MID:4041, 2.31 Continue, TKN:c9 0f af b2, Block #0, /push
    280 332.699763     2001:569:6ff9:6647:7520:b874:b77:b628 64:ff9b::3411:8e3e    56830    5686     CoAP     163    CON, MID:4042, POST, TKN:ca 0f af b2, End of Block #1, /push?ep=351711090003168
    281 332.958887     64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     104    ACK, MID:4042, 2.01 Created, TKN:ca 0f af b2, End of Block #1, /push
    282 337.460227     2001:569:6ff9:6647:7520:b874:b77:b628 64:ff9b::3411:8e3e    56830    5686     CoAP     260    CON, MID:4043, POST, TKN:cb 0f b4 b2, Block #0, /push?ep=351711090003168
    283 337.698859     64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     104    ACK, MID:4043, 2.31 Continue, TKN:cb 0f b4 b2, Block #0, /push
    284 337.701265     2001:569:6ff9:6647:7520:b874:b77:b628 64:ff9b::3411:8e3e    56830    5686     CoAP     163    CON, MID:4044, POST, TKN:cc 0f b4 b2, End of Block #1, /push?ep=351711090003168
    285 337.917032     64:ff9b::3411:8e3e    2001:569:6ff9:6647:7520:b874:b77:b628 5686     56830    CoAP     123    ACK, MID:4044, 4.08 Request Entity Incomplete, TKN:cc 0f b4 b2, End of Block #1, /push (text/plain)
```

After investigation, I suspect this is the `CleaningTask` of block status from BlockwiseLayer which is not stopped when we received the last block and so could interfere with next transfer using same URI same IP/port.

Reading the code, I can not find other explanation. The error appears ~ 5 minutes later which is the BLOCKWISE_STATUS_LIFETIME. This confirm the idea.

I will propose a PR for this issue.

### PR DESCRIPTION
**Pull request by sbernard31**
This PR aims to fix #537 (It should also fix same kind of error for block2)

### CODE REVIEW

**Comment by boaks** [comment]
LGTM

**Comment by boaks** [comment]
some curio: with that bugifx, my benchmarkclient hangs in the shutdown ;-).

**Comment by sbernard31** [comment]
I will look at this.

**Comment by sbernard31** [comment]
Could you provide how to reproduce ? (client parameters + server parameters)

**Comment by boaks** [comment]
Sure, but I already found the dead-lock :-).

> Thread [Client-49#1] (Suspended)	
> 	owns: Block2BlockwiseStatus  (id=610)	
> 	waiting for: LeastRecentlyUsedCache<K,V>  (id=611)	
> 	BlockwiseLayer.clearBlock2Status(KeyUri) line: 1056	
> 	BlockwiseLayer.handleInboundRequestForNextBlock(Exchange, Request, KeyUri, Block2BlockwiseStatus) line: 447	
> 	BlockwiseLayer.receiveRequest(Exchange, Request) line: 324	
> 	ReliabilityLayer.receiveRequest(Exchange, Request) line: 235	
> 	BaseCoapStack$StackBottomAdapter(AbstractLayer).receiveRequest(Exchange, Request) line: 81	
> 	CoapUdpStack(BaseCoapStack).receiveRequest(Exchange, Request) line: 99	
> 	CoapEndpoint$InboxImpl.receiveRequest(Request, RawData) line: 859	
> 	CoapEndpoint$InboxImpl.receiveMessage(RawData) line: 792	
> 	CoapEndpoint$InboxImpl.access$0(CoapEndpoint$InboxImpl, RawData) line: 783	
> 	CoapEndpoint$InboxImpl$1.run() line: 771	
> 	CoapEndpoint$5.run() line: 1003	
> 	Executors$RunnableAdapter<T>.call() line: 511	
> 	ScheduledThreadPoolExecutor$ScheduledFutureTask<V>(FutureTask<V>).run() line: 266	
> 	ScheduledThreadPoolExecutor$ScheduledFutureTask<V>.access$201(ScheduledThreadPoolExecutor$ScheduledFutureTask) line: 180	
> 	ScheduledThreadPoolExecutor$ScheduledFutureTask<V>.run() line: 293	
> 	ScheduledThreadPoolExecutor(ThreadPoolExecutor).runWorker(ThreadPoolExecutor$Worker) line: 1149	
> 	ThreadPoolExecutor$Worker.run() line: 624	
> 	Thread.run() line: 748	
> 


> Thread [Client-49#2] (Suspended)	
> 	owns: LeastRecentlyUsedCache<K,V>  (id=611)	
> 	waiting for: Block2BlockwiseStatus  (id=610)	
> 	Block2BlockwiseStatus(BlockwiseStatus).setComplete(boolean) line: 169	
> 	BlockwiseLayer.clearBlock2Status(KeyUri) line: 1061	
> 	BlockwiseLayer.sendResponse(Exchange, Response) line: 520	
> 	ObserveLayer.sendResponse(Exchange, Response) line: 131	
> 	ExchangeCleanupLayer(AbstractLayer).sendResponse(Exchange, Response) line: 71	
> 	BaseCoapStack$StackTopAdapter.sendResponse(Exchange, Response) line: 154	
> 	CoapUdpStack(BaseCoapStack).sendResponse(Exchange, Response) line: 87	
> 	CoapEndpoint.sendResponse(Exchange, Response) line: 579	
> 	Exchange.sendResponse(Response) line: 288	
> 	CoapExchange.respond(Response) line: 330	
> 	CoapExchange.respond(CoAP$ResponseCode, byte[], int) line: 289	
> 	Feed.handleGET(CoapExchange) line: 125	
> 	Feed(CoapResource).handleRequest(Exchange) line: 216	
> 	ObserveRelation.notifyObservers() line: 146	
> 	Feed(CoapResource).notifyObserverRelations(ObserveRelationFilter) line: 767	
> 	Feed(CoapResource).changed(ObserveRelationFilter) line: 748	
> 	Feed(CoapResource).changed() line: 729	
> 	Feed$1.run() line: 74	
> 	Executors$RunnableAdapter<T>.call() line: 511	
> 	ScheduledThreadPoolExecutor$ScheduledFutureTask<V>(FutureTask<V>).runAndReset() line: 308	
> 	ScheduledThreadPoolExecutor$ScheduledFutureTask<V>.access$301(ScheduledThreadPoolExecutor$ScheduledFutureTask) line: 180	
> 	ScheduledThreadPoolExecutor$ScheduledFutureTask<V>.run() line: 294	
> 	ScheduledThreadPoolExecutor(ThreadPoolExecutor).runWorker(ThreadPoolExecutor$Worker) line: 1149	
> 	ThreadPoolExecutor$Worker.run() line: 624	
> 	Thread.run() line: 748	
>

**Comment by boaks** [comment]
I start the ExtendedTestServer with 
`-d64 -Xmx2g -loopback -noPlugtest`
and the BenchmarkClient with
`coap://localhost:5783/reverse-observe?obs=25&res=feed&rlen=400 100 3 x 500`

(I used the PR #539, #540, #541 merged)

**Comment by sbernard31** [comment]
I will look this deeper but I suppose calling [setComplete](https://github.com/eclipse/californium/pull/538/commits/0dcd2e0817a447d4b810fedc7cf9c548ddd777db) outside the synchronize block is smarter.

**Comment by boaks** [comment]
```
		int size = -1;
		Block1BlockwiseStatus removedTracker;
		synchronized (block1Transfers) {
			removedTracker = block1Transfers.remove(key);
			size = block1Transfers.size();
		}
		if (removedTracker != null) {
			LOGGER.debug("removing block1 tracker [{}], block1 transfers still in progress: {}", key, size);
			removedTracker.setComplete(true);
		}
		return removedTracker;

```

Seems to do it for me ...

**Comment by sbernard31** [comment]
That's what I thought.

**Comment by sbernard31** [comment]
Without surprise with this kind of bug (depending on timing), I'm not able to reproduce it.

But your log is explicit enough, I will provide a PR which extract the setcomplete from the synchronized block which is better anyway.

**Pull request merged**
