### PR TITLE
Typo in DTLSConnector

### PR DESCRIPTION
**Pull request by TetraSomia**

### CODE REVIEW

**Comment by boaks** [comment]
Hi @TetraSomia ,

thanks! Eclipse requires that you sign a ECA, see 
[Contribute](https://github.com/eclipse/californium/blob/master/CONTRIBUTING.md)
[ECA](http://www.eclipse.org/legal/ECA.php)

If you sign it, ensure you use the e-mail you also use to sign the commit.
 
(If you think, that's somehow overdone, I can fix the typos as well, but then you will not be shown as author :-) ).

**Comment by TetraSomia** [comment]
Hi @boaks ,
Thanks for the reply! Yeah it's a bit overkill for a typo, you can fix it without mentioning me :)

**Comment by boaks** [comment]
Thanks!

**Comment by boaks** [comment]
It's in master.

**Pull request closed without merging**
